### ISSUE TITLE
NSNumber error

### ISSUE THREAD

**Issue by systemride** [aksonov/react-native-svg-elements#1]
In my Svg I have:

`<Svg width={8} height={8}>` and I get the following:

<img width="368" alt="screen shot 2015-09-24 at 8 48 42 pm" src="https://cloud.githubusercontent.com/assets/1361/10092685/19e32ce8-62fe-11e5-8d8e-ad278ebd2cea.png">

Any ideas? I'm on xcode 7.

**Comment by aksonov** [comment]
Please check with latest version, should be fixed

**Comment by systemride** [comment]
:+1: Good to go thanks.
