### ISSUE TITLE
Width and height have unexpected results

### ISSUE THREAD

**Issue by systemride** [aksonov/react-native-svg-elements#3]
I'm using this simply for SVG icons using Path. When specifying the width and height on a `<Svg>` element, there seems to be unexpected results. For example setting an element's width to 40 results in a very large svg element, while setting it 500 results in a very small svg element.

**Comment by aksonov** [comment]
width and height parameter of Svg elements should be the same as for 'svg' element from SVG format - it defines width/height of whole canvas. You may use Path directly inside G element with defined 'scale' attribute.

**Comment by systemride** [comment]
:+1: This helped thanks.
